kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummy-app-3-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: dummy-app-3-dsp-job
    namespace: rhtap-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dummy-app-3-imagestream-job-role
